from __future__ import annotations

import logging
import math
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from trajex.trace import Step, Trace

logger = logging.getLogger("trajex")


@dataclass
class ScanFinding:
    level: Literal["FAIL", "WARN", "INFO"]
    check_name: str
    title: str
    detail: str
    step_indices: list[int]
    suggested_assertion: str = ""


@dataclass
class ScanReport:
    trace_id: str
    prompt: str
    findings: list[ScanFinding] = field(default_factory=list)

    @property
    def failures(self) -> list[ScanFinding]:
        return [f for f in self.findings if f.level == "FAIL"]

    @property
    def warnings(self) -> list[ScanFinding]:
        return [f for f in self.findings if f.level == "WARN"]

    @property
    def has_failures(self) -> bool:
        return any(f.level == "FAIL" for f in self.findings)

    def suggested_assertions(self) -> list[str]:
        return [f.suggested_assertion for f in self.findings if f.suggested_assertion]


def generate_test_file(report: ScanReport, trace_path: str = "trace.json") -> str:
    # Deduplicate suggestions while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for s in report.suggested_assertions():
        if s not in seen:
            seen.add(s)
            unique.append(s)

    assertions_block = ""
    for suggestion in unique:
        assertions_block += f"        {suggestion},\n"

    prompt_repr = repr(report.prompt[:60])
    return (
        f"# Generated by: trajex init\n"
        f"# Trace: {trace_path}\n"
        f"# Prompt: {prompt_repr}\n"
        f"# Review each assertion and adjust thresholds before committing.\n"
        f"\n"
        f"import pytest\n"
        f"from trajex import Trace, assert_trajectory\n"
        f"from trajex.assertions import (\n"
        f"    sequence, never_before, no_loop, max_steps,\n"
        f"    tool_called, tool_never_called,\n"
        f")\n"
        f"\n"
        f"\n"
        f"@pytest.mark.trajectory\n"
        f"def test_agent_trajectory():\n"
        f'    trace = Trace.from_json("{trace_path}")\n'
        f"    assert_trajectory(trace, [\n"
        f"{assertions_block}"
        f"    ])\n"
    )


def scan(
    trace: "Trace",
    schema: dict | None = None,
    *,
    include_info: bool = False,
) -> ScanReport:
    report = ScanReport(trace_id=trace.id, prompt=trace.prompt)
    tool_calls = trace.tool_calls()
    tool_names = trace.tool_names()
    total_steps = len(trace.steps)

    # ── Structural checks ─────────────────────────────────────────────────────

    _check_loop(report, tool_calls, tool_names, total_steps)
    _check_runaway(report, total_steps)
    _check_no_tool_calls(report, trace, tool_calls)
    _check_tool_tornado(report, trace, tool_calls)
    _check_abrupt_finish(report, trace)
    _check_duplicate_consecutive(report, tool_calls)
    _check_error_steps(report, trace)
    _check_orphaned_tool_results(report, trace)
    _check_zero_output_tools(report, tool_calls, include_info)
    _check_latency_outliers(report, tool_calls, include_info)

    # ── Behavioral correctness checks (derived from real-agent field study) ───
    _check_write_without_context(report, tool_calls)
    _check_hallucinated_context(report, tool_calls)
    _check_commit_without_validation(report, tool_calls)
    _check_write_before_read(report, tool_calls)
    _check_destructive_tool_without_confirm(report, tool_calls)
    _check_irreversible_in_finish(report, trace)

    # ── Semantic checks (reasoning text required) ─────────────────────────────
    _check_semantic(report, trace, include_info)

    # ── Name-aware checks (only when schema provided) ─────────────────────────
    if schema:
        _check_schema_aware(report, trace, tool_calls, schema)

    if not include_info:
        report.findings = [f for f in report.findings if f.level != "INFO"]

    return report


# ── Check implementations ─────────────────────────────────────────────────────


def _is_query_input(inp) -> bool:
    """Return True if inp looks like a search/research query rather than a parameter dict."""
    if isinstance(inp, str):
        return len(inp.split()) >= 2
    if isinstance(inp, dict):
        # {'query': '...'} or {'q': '...'} — single-key dicts whose value is a multi-word string
        if len(inp) == 1:
            val = next(iter(inp.values()))
            return isinstance(val, str) and len(val.split()) >= 2
    return False


def _check_loop(
    report: ScanReport,
    tool_calls: list["Step"],
    tool_names: list[str],
    total_steps: int,
) -> None:
    if not tool_names:
        return

    # --- Consecutive repetition ---
    # Find the longest run of the same tool name.
    best_tool: str = tool_names[0]
    best_run = 1
    best_start = 0
    current_tool = tool_names[0]
    current_run = 1
    current_start = 0

    for i, name in enumerate(tool_names[1:], 1):
        if name == current_tool:
            current_run += 1
            if current_run > best_run:
                best_run = current_run
                best_tool = current_tool
                best_start = current_start
        else:
            current_tool = name
            current_run = 1
            current_start = i

    research_pattern_tool: str | None = None  # tool cleared as multi-query research

    if best_run >= 3:
        run_steps = tool_calls[best_start: best_start + best_run]
        indices = [s.index for s in run_steps]

        # Check if every call in the run has distinct inputs.
        # Research agents legitimately call the same search tool N times with
        # different queries — that is NOT a loop. A true loop repeats the same
        # input (or has a high proportion of identical inputs).
        inputs = [s.input for s in run_steps]
        # Serialize for comparison; two None inputs count as identical.
        serialized = [str(inp) for inp in inputs]
        unique_inputs = len(set(serialized))
        all_unique = unique_inputs == len(serialized)

        # A legitimate multi-query research pattern has two properties:
        #   1. All inputs are unique (different queries, not retries)
        #   2. Inputs are query-like: either plain string queries or single-key dicts
        #      like {'query': '...'} — NOT parameter dicts with booleans or multiple
        #      keys representing slight tweaks to the same transactional call.
        inputs_are_query_strings = all(_is_query_input(inp) for inp in inputs)
        if all_unique and best_run < 6 and inputs_are_query_strings:
            # Multi-query pattern with different text queries and < 6 calls:
            # this is the expected behavior for research-style agents.
            # Track which tool was cleared so the frequency check skips it too.
            research_pattern_tool = best_tool
        else:
            # WARN only when inputs are unique text queries (unbounded search expansion).
            # FAIL otherwise: repeated calls with identical inputs or with param
            # variations on a transactional tool are always a retry loop.
            level = "WARN" if (all_unique and inputs_are_query_strings) else "FAIL"
            report.findings.append(
                ScanFinding(
                    level=level,
                    check_name="loop_detection",
                    title=f"Loop detected: '{best_tool}' called {best_run} times consecutively",
                    detail=(
                        f"'{best_tool}' was called {best_run} times in a row.\n"
                        f"Consecutive repeated tool calls almost always indicate a logic loop.\n"
                        f"Steps involved: {indices}"
                    ),
                    step_indices=indices,
                    suggested_assertion=f"no_loop({best_tool!r}, max_calls=1)",
                )
            )
            return  # don't also fire frequency check for the same tool

    # --- Frequency check: a single tool dominates >40% of total steps ---
    # Skip tools already cleared as a multi-query research pattern above.
    counts = Counter(tool_names)
    threshold = math.ceil(total_steps * 0.4)
    for tool, count in counts.most_common():
        if tool == research_pattern_tool:
            continue  # legitimate multi-query research — not a frequency loop
        if count > threshold:
            matching = [s.index for s in tool_calls if s.name == tool]
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="loop_detection",
                    title=f"Loop detected: '{tool}' accounts for {count}/{total_steps} steps ({count/total_steps:.0%})",
                    detail=(
                        f"'{tool}' was called {count} times -- "
                        f"more than 40% of all {total_steps} steps.\n"
                        f"Steps involved: {matching}"
                    ),
                    step_indices=matching,
                    suggested_assertion=f"no_loop({tool!r}, max_calls={max(1, count // 2)})",
                )
            )
            break  # one finding per scan is enough


def _check_runaway(report: ScanReport, total_steps: int) -> None:
    if total_steps > 20:
        report.findings.append(
            ScanFinding(
                level="FAIL",
                check_name="runaway_trace",
                title=f"Agent took {total_steps} steps (threshold: 20)",
                detail=(
                    f"This trace has {total_steps} steps. Every step above the threshold\n"
                    f"burns tokens and adds end-user latency on every single invocation.\n"
                    f"Over-budget by {total_steps - 20} steps."
                ),
                step_indices=list(range(total_steps)),
                suggested_assertion=f"max_steps({max(10, total_steps // 2)})",
            )
        )


def _check_no_tool_calls(
    report: ScanReport, trace: "Trace", tool_calls: list["Step"]
) -> None:
    if len(tool_calls) == 0 and len(trace.prompt.split()) > 5:
        report.findings.append(
            ScanFinding(
                level="WARN",
                check_name="no_tool_calls",
                title="Agent produced output without calling any tools",
                detail=(
                    "No tool_call steps found in this trace.\n"
                    "The agent may have hallucinated a response rather than acting on real data.\n"
                    "If tools are expected for this prompt, this is a silent correctness failure."
                ),
                step_indices=[],
                suggested_assertion="",
            )
        )


def _check_tool_tornado(
    report: ScanReport, trace: "Trace", tool_calls: list["Step"]
) -> None:
    unique = trace.unique_tools_called()
    if len(unique) > 8:
        report.findings.append(
            ScanFinding(
                level="WARN",
                check_name="tool_tornado",
                title=f"Agent called {len(unique)} distinct tools (threshold: 8)",
                detail=(
                    f"Calling {len(unique)} different tools in a single run suggests the agent\n"
                    f"lacks a clear plan. This often means excessive API calls and high latency.\n"
                    f"Tools called: {', '.join(unique)}"
                ),
                step_indices=[s.index for s in tool_calls],
                suggested_assertion="",
            )
        )


def _check_abrupt_finish(report: ScanReport, trace: "Trace") -> None:
    if not trace.steps:
        return
    from trajex.trace import StepType
    last = trace.steps[-1]
    if last.step_type not in (StepType.AGENT_FINISH, StepType.LLM_RESPONSE):
        report.findings.append(
            ScanFinding(
                level="WARN",
                check_name="abrupt_finish",
                title=f"Trace ends on step type '{last.step_type.value}' — not a clean finish",
                detail=(
                    f"The final step (index {last.index}) has type '{last.step_type.value}'.\n"
                    f"A well-formed trace ends with agent_finish or llm_response.\n"
                    f"This suggests the agent was interrupted or crashed mid-run."
                ),
                step_indices=[last.index],
                suggested_assertion="",
            )
        )


def _check_duplicate_consecutive(report: ScanReport, tool_calls: list["Step"]) -> None:
    for i in range(1, len(tool_calls)):
        prev = tool_calls[i - 1]
        curr = tool_calls[i]
        if prev.name == curr.name and prev.input == curr.input:
            report.findings.append(
                ScanFinding(
                    level="WARN",
                    check_name="duplicate_consecutive",
                    title=f"'{curr.name}' called twice in a row with identical inputs",
                    detail=(
                        f"Steps {prev.index} and {curr.index} are identical invocations of '{curr.name}'.\n"
                        f"Input: {str(curr.input)[:120]}\n"
                        f"This is usually an off-by-one error or a missing break condition."
                    ),
                    step_indices=[prev.index, curr.index],
                    suggested_assertion=f"no_loop({curr.name!r}, max_calls=1)",
                )
            )


def _check_error_steps(report: ScanReport, trace: "Trace") -> None:
    error_steps = trace.error_steps()
    if not error_steps:
        return
    indices = [s.index for s in error_steps]
    first_error = error_steps[0]
    report.findings.append(
        ScanFinding(
            level="FAIL",
            check_name="error_in_trace",
            title=f"{len(error_steps)} step(s) failed with errors",
            detail=(
                f"Steps {indices} contain errors.\n"
                f"First error at step {first_error.index} ('{first_error.name}'): "
                f"{str(first_error.error)[:120]}"
            ),
            step_indices=indices,
            suggested_assertion="",
        )
    )


def _check_orphaned_tool_results(report: ScanReport, trace: "Trace") -> None:
    """tool_result steps with no preceding tool_call are orphaned — usually a pairing bug in an emitter."""
    from trajex.trace import StepType
    tool_call_indices: set[int] = {s.index for s in trace.tool_calls()}
    orphans: list[int] = []
    for step in trace.steps:
        if step.step_type == StepType.TOOL_RESULT:
            # Check if the previous step is a tool_call
            prev_index = step.index - 1
            if prev_index not in tool_call_indices:
                orphans.append(step.index)
    if orphans:
        report.findings.append(
            ScanFinding(
                level="WARN",
                check_name="orphaned_tool_result",
                title=f"{len(orphans)} tool_result step(s) with no preceding tool_call",
                detail=(
                    f"Steps {orphans} are tool_result steps not immediately preceded by a tool_call.\n"
                    f"This usually means an emitter pairing bug — the tool call is lost from the trace.\n"
                    f"Assertions that rely on tool_call steps will miss these invocations entirely."
                ),
                step_indices=orphans,
                suggested_assertion="",
            )
        )


def _check_zero_output_tools(
    report: ScanReport, tool_calls: list["Step"], include_info: bool
) -> None:
    """Tool calls with null output AND no error may indicate silent failures."""
    if not include_info:
        return
    silent = [s for s in tool_calls if s.output is None and s.error is None]
    if silent:
        indices = [s.index for s in silent]
        report.findings.append(
            ScanFinding(
                level="INFO",
                check_name="null_output_tool_calls",
                title=f"{len(silent)} tool call(s) have null output and no error",
                detail=(
                    f"Steps {indices} completed without output or error.\n"
                    f"This may be correct (void-return tools) or may indicate a silent failure\n"
                    f"where the emitter failed to capture the tool result."
                ),
                step_indices=indices,
                suggested_assertion="",
            )
        )


def _check_latency_outliers(
    report: ScanReport, tool_calls: list["Step"], include_info: bool
) -> None:
    """Tool calls that take 10x longer than average are latency outliers worth noting."""
    if not include_info:
        return
    durations = [(s, s.duration_ms) for s in tool_calls if s.duration_ms is not None]
    if len(durations) < 3:
        return
    values = [d for _, d in durations]
    avg = sum(values) / len(values)
    if avg < 1.0:
        return
    outliers = [(s, d) for s, d in durations if d > avg * 10]
    if outliers:
        for step, dur in outliers:
            report.findings.append(
                ScanFinding(
                    level="INFO",
                    check_name="latency_outlier",
                    title=f"'{step.name}' took {dur:.0f}ms — {dur/avg:.1f}x average",
                    detail=(
                        f"Step {step.index} ('{step.name}') took {dur:.0f}ms.\n"
                        f"Average tool duration in this trace: {avg:.0f}ms.\n"
                        f"This outlier inflates end-user latency significantly."
                    ),
                    step_indices=[step.index],
                    suggested_assertion="",
                )
            )


def _check_semantic(report: ScanReport, trace: "Trace", include_info: bool) -> None:
    reasoning_texts = trace.reasoning_text()
    if not reasoning_texts:
        return

    # Goal drift: compare prompt keywords against the UNION of ALL reasoning texts.
    # Using only the final step's reasoning produced false positives: multi-step
    # agents legitimately shift from "planning" to "executing" language. Checking
    # the union across all steps provides a much more accurate signal.
    prompt_words = set(re.findall(r"\b[a-z]{4,}\b", trace.prompt.lower()))
    all_reasoning_words: set[str] = set()
    for rt in reasoning_texts:
        all_reasoning_words |= set(re.findall(r"\b[a-z]{4,}\b", rt.lower()))

    if len(prompt_words) >= 4 and all_reasoning_words:
        overlap = len(prompt_words & all_reasoning_words) / len(prompt_words)
        if overlap < 0.1:
            last_words = set(re.findall(r"\b[a-z]{4,}\b", reasoning_texts[-1].lower()))
            report.findings.append(
                ScanFinding(
                    level="WARN",
                    check_name="goal_drift",
                    title="Possible goal drift: agent reasoning never references prompt keywords",
                    detail=(
                        f"Prompt keywords: {', '.join(sorted(prompt_words)[:8])}\n"
                        f"Reasoning keywords (all steps): {', '.join(sorted(all_reasoning_words)[:8])}\n"
                        f"Overlap: {overlap:.0%} -- the agent may be solving the wrong problem."
                    ),
                    step_indices=[],
                    suggested_assertion="",
                )
            )

    # Hedging language: signals plan abandonment mid-run.
    _HEDGE = re.compile(
        r"\b(actually|instead|alternatively|changed my mind|let me try|"
        r"on second thought|wait,|never mind|forget that|scratch that)\b",
        re.I,
    )
    for i, text in enumerate(reasoning_texts[:-1]):  # skip final (could just be conclusive)
        if _HEDGE.search(text):
            if include_info:
                report.findings.append(
                    ScanFinding(
                        level="INFO",
                        check_name="abandoned_plan",
                        title="Reasoning contains hedging language — possible plan change mid-run",
                        detail=f"Snippet: {text[:200]}",
                        step_indices=[],
                        suggested_assertion="",
                    )
                )
            break

    # Repetitive reasoning: nearly identical reasoning across consecutive steps.
    for i in range(1, len(reasoning_texts)):
        prev_words = set(reasoning_texts[i - 1].lower().split())
        curr_words = set(reasoning_texts[i].lower().split())
        union = prev_words | curr_words
        if not union:
            continue
        jaccard = len(prev_words & curr_words) / len(union)
        if jaccard > 0.85 and len(prev_words) > 10:
            if include_info:
                report.findings.append(
                    ScanFinding(
                        level="INFO",
                        check_name="repetitive_reasoning",
                        title=f"Consecutive reasoning steps are {jaccard:.0%} similar — possible stuck loop",
                        detail=(
                            f"Reasoning step {i-1} and {i} have nearly identical content.\n"
                            f"Jaccard similarity: {jaccard:.2f}. This strongly suggests a reasoning loop."
                        ),
                        step_indices=[],
                        suggested_assertion="",
                    )
                )
            break


def _check_schema_aware(
    report: ScanReport,
    trace: "Trace",
    tool_calls: list["Step"],
    schema: dict,
) -> None:
    destructive: set[str] = set(schema.get("destructive_tools", []))
    guards: set[str] = set(schema.get("guard_tools", []))
    financial: set[str] = set(schema.get("financial_tools", []))
    notification: set[str] = set(schema.get("notification_tools", []))

    # Build a set of all guard-tool indices for fast lookup.
    guard_indices: set[int] = {s.index for s in tool_calls if s.name in guards}

    # --- Destructive tool called before any guard tool ---
    for step in tool_calls:
        if step.name not in destructive:
            continue
        # A guard must have been called BEFORE this step.
        any_guard_before = any(gi < step.index for gi in guard_indices)
        if not any_guard_before and guards:
            guard_list = ", ".join(sorted(guards))
            first_guard = next(iter(sorted(guards)))
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="unguarded_destructive_tool",
                    title=f"'{step.name}' called without any preceding guard tool",
                    detail=(
                        f"Destructive tool '{step.name}' executed at step {step.index},\n"
                        f"but none of the guard tools ({guard_list}) were called before it.\n"
                        f"This is a silent authorization bypass — the agent assumed permission\n"
                        f"that was never explicitly granted in this run."
                    ),
                    step_indices=[step.index],
                    suggested_assertion=(
                        f"never_before({step.name!r}, {first_guard!r})"
                    ),
                )
            )

    # --- Guard called AFTER the destructive tool (wrong order) ---
    for step in tool_calls:
        if step.name not in destructive:
            continue
        guard_after = [gi for gi in guard_indices if gi > step.index]
        if guard_after:
            guard_step_name = next(
                s.name for s in tool_calls if s.index == min(guard_after)
            )
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="guard_too_late",
                    title=f"'{step.name}' ran before guard '{guard_step_name}' — order reversed",
                    detail=(
                        f"'{step.name}' executed at step {step.index}.\n"
                        f"'{guard_step_name}' ran later at step {min(guard_after)}.\n"
                        f"The destructive action happened before authorization was confirmed."
                    ),
                    step_indices=[step.index, min(guard_after)],
                    suggested_assertion=f"never_before({step.name!r}, {guard_step_name!r})",
                )
            )

    # --- Financial tools: flag for mandatory audit ---
    for step in tool_calls:
        if step.name in financial:
            report.findings.append(
                ScanFinding(
                    level="WARN",
                    check_name="financial_tool_called",
                    title=f"Financial tool '{step.name}' called — verify authorization",
                    detail=(
                        f"'{step.name}' (step {step.index}) is a financial tool.\n"
                        f"Ensure this was intentional and that an authorization guard preceded it."
                    ),
                    step_indices=[step.index],
                    suggested_assertion=f"tool_called({step.name!r})",
                )
            )

    # --- Notification tools called excessively ---
    for tool_name in notification:
        notif_steps = [s for s in tool_calls if s.name == tool_name]
        if len(notif_steps) > 1:
            indices = [s.index for s in notif_steps]
            report.findings.append(
                ScanFinding(
                    level="WARN",
                    check_name="notification_spam",
                    title=f"Notification tool '{tool_name}' called {len(notif_steps)} times",
                    detail=(
                        f"'{tool_name}' was called {len(notif_steps)} times in this trace.\n"
                        f"Steps: {indices}\n"
                        f"Each invocation of this agent sends {len(notif_steps)} notification(s)."
                    ),
                    step_indices=indices,
                    suggested_assertion=f"no_loop({tool_name!r}, max_calls=1)",
                )
            )


# ── Field-study-derived behavioral checks ─────────────────────────────────────
#
# These four checks were added after running Trajex against 6 real open-source
# agents. Each check catches a bug class that was observed in at least two of
# the six agents and was missed by the original scanner.


def _check_write_without_context(
    report: ScanReport,
    tool_calls: list["Step"],
) -> None:
    """Detect report/section generation called with zero search context.

    Bug class: Report-Without-Verification.
    Observed in: gpt-researcher, open_deep_research.

    When search APIs fail or return empty results, both agents continue to
    call write_report / write_section with context_chars=0 or context_sources=0.
    The result is a hallucinated report that the agent marks as successful.
    """
    _WRITE_TOOLS = re.compile(
        r"^(write_report|write_final_report|write_section|generate_report"
        r"|write_summary|generate_summary)$",
        re.I,
    )
    for step in tool_calls:
        if not _WRITE_TOOLS.match(step.name):
            continue
        inp = step.input if isinstance(step.input, dict) else {}
        # Direct context-size fields in input
        context_chars = inp.get("context_chars", -1)
        context_sources = inp.get("context_sources", -1)
        if context_chars == 0 or context_sources == 0:
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="write_without_context",
                    title=f"'{step.name}' called with zero search context",
                    detail=(
                        f"'{step.name}' at step {step.index} was invoked with "
                        f"{'context_chars=0' if context_chars == 0 else 'context_sources=0'}.\n"
                        f"This means no research data was available before report generation.\n"
                        f"The output is hallucinated content with no grounding in real sources.\n"
                        f"Guard: verify search results are non-empty before calling this tool."
                    ),
                    step_indices=[step.index],
                    suggested_assertion=f"tool_called('get_search_results')",
                )
            )


def _check_hallucinated_context(
    report: ScanReport,
    tool_calls: list["Step"],
) -> None:
    """Detect synthesis tools called after all retrieval tools returned empty results.

    Bug class: Hallucinated-Context Fabrication.
    Observed in: live run (claude_research_empty_search.json,
    2026-04-18T06:22:36), claude-3-5-haiku.

    When all search/retrieval calls return empty strings, the LLM silently
    generates plausible-looking context from its own training data and passes
    it to the report writer. The report appears researched but contains zero
    retrieved information. No error is surfaced.

    This is distinct from write_without_context (which fires on context_chars=0):
    the context field here is NON-EMPTY — the model fabricated it.
    """
    _RETRIEVAL_TOOLS = re.compile(
        r"^(search_web|search|get_search_results|web_search|bing_search"
        r"|google_search|tavily_search|retrieve|fetch_url|scrape)$",
        re.I,
    )
    _WRITE_TOOLS = re.compile(
        r"^(write_report|write_final_report|write_section|generate_report"
        r"|write_summary|generate_summary)$",
        re.I,
    )

    retrieval_steps = [s for s in tool_calls if _RETRIEVAL_TOOLS.match(s.name)]
    if not retrieval_steps:
        return

    for write_step in tool_calls:
        if not _WRITE_TOOLS.match(write_step.name):
            continue

        # Collect retrieval outputs that preceded this write step
        prior_retrievals = [s for s in retrieval_steps if s.index < write_step.index]
        if not prior_retrievals:
            continue

        # All prior retrievals must have returned empty / None to fire
        all_empty = all(
            (s.output is None or str(s.output).strip() == "")
            for s in prior_retrievals
        )
        if not all_empty:
            continue

        # Check if write_report received a non-empty context anyway (hallucination signal)
        inp = write_step.input
        context_is_non_empty = False
        if isinstance(inp, list) and len(inp) >= 2:
            context_is_non_empty = bool(str(inp[1]).strip())
        elif isinstance(inp, dict):
            ctx = inp.get("context", "")
            context_is_non_empty = bool(str(ctx).strip())
        elif isinstance(inp, str):
            context_is_non_empty = bool(inp.strip())

        empty_indices = [s.index for s in prior_retrievals]
        if context_is_non_empty:
            # Model fabricated context — hallucination confirmed
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="hallucinated_context",
                    title=f"'{write_step.name}' called with LLM-fabricated context after {len(prior_retrievals)} empty searches",
                    detail=(
                        f"All {len(prior_retrievals)} retrieval call(s) before step {write_step.index} "
                        f"returned empty results (steps {empty_indices}).\n"
                        f"'{write_step.name}' was nonetheless called with a non-empty context string.\n"
                        f"The LLM synthesized this context from training memory -- it is not retrieved data.\n"
                        f"The output appears researched but contains zero real sources.\n"
                        f"Guard: assert len(search_results) > 0 before calling the synthesis tool."
                    ),
                    step_indices=empty_indices + [write_step.index],
                    suggested_assertion=f"never_before({write_step.name!r}, 'search_web')",
                )
            )
        else:
            # Empty context passed -- covered by write_without_context, but note it here
            # as a contributing signal. Do not double-fire -- write_without_context handles it.
            pass


def _check_commit_without_validation(
    report: ScanReport,
    tool_calls: list["Step"],
) -> None:
    """Detect code commits that happen without a preceding test/lint execution.

    Bug class: Commit-Before-Validation.
    Observed in: open-swe, langchain-ai/deepagents.

    Coding agents that commit without running tests can push broken code silently.
    The commit tool is an irreversible action; test execution is the required guard.
    """
    _COMMIT_TOOLS = re.compile(r"^(commit_and_open_pr|commit|git_commit|push_commit)$", re.I)
    _VALIDATE_TOOLS = re.compile(
        r"^(execute|execute_tests|run_tests|run_test|pytest|bash|shell|run_command)$",
        re.I,
    )

    commit_steps = [s for s in tool_calls if _COMMIT_TOOLS.match(s.name)]
    if not commit_steps:
        return

    validate_steps = [s for s in tool_calls if _VALIDATE_TOOLS.match(s.name)]

    for commit_step in commit_steps:
        # Check if any validation tool ran BEFORE this commit
        any_validate_before = any(
            v.index < commit_step.index for v in validate_steps
        )
        if not any_validate_before:
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="commit_without_validation",
                    title=f"'{commit_step.name}' called without preceding test execution",
                    detail=(
                        f"'{commit_step.name}' at step {commit_step.index} committed code\n"
                        f"without any preceding execute/run_tests call in this trace.\n"
                        f"Tests were never run. If the change introduced a bug, it is\n"
                        f"now in the PR with no automated signal that it is broken.\n"
                        f"Guard: require execute() before commit_and_open_pr()."
                    ),
                    step_indices=[commit_step.index],
                    suggested_assertion=f"never_before('execute', {commit_step.name!r})",
                )
            )


def _check_write_before_read(
    report: ScanReport,
    tool_calls: list["Step"],
) -> None:
    """Detect write_file called on a path without a preceding read_file on that path.

    Bug class: Destructive-Write-Without-Read.
    Observed in: open-swe, langchain-ai/deepagents.

    Writing a file without reading it first clobbers any existing content.
    For config files or non-generated files, this is a silent destructive overwrite.
    """
    _WRITE_FILE_TOOLS = re.compile(r"^(write_file|create_file|overwrite_file)$", re.I)
    _READ_FILE_TOOLS = re.compile(r"^(read_file|open_file|cat_file|view_file)$", re.I)

    read_paths: set[str] = set()
    for step in tool_calls:
        if _READ_FILE_TOOLS.match(step.name):
            path = None
            if isinstance(step.input, dict):
                path = step.input.get("path") or step.input.get("file_path")
            elif isinstance(step.input, str):
                path = step.input
            if path:
                read_paths.add(str(path))

        elif _WRITE_FILE_TOOLS.match(step.name):
            path = None
            if isinstance(step.input, dict):
                path = step.input.get("path") or step.input.get("file_path")
            elif isinstance(step.input, str):
                path = step.input
            if path and str(path) not in read_paths:
                report.findings.append(
                    ScanFinding(
                        level="WARN",
                        check_name="write_before_read",
                        title=f"'{step.name}' overwrites '{path}' without prior read",
                        detail=(
                            f"'{step.name}' at step {step.index} writes to '{path}'\n"
                            f"but read_file was never called on that path earlier in this trace.\n"
                            f"If the file contains existing content, it will be silently destroyed.\n"
                            f"This is especially dangerous for config files, credentials, or migrations."
                        ),
                        step_indices=[step.index],
                        suggested_assertion=f"sequence('read_file', {step.name!r})",
                    )
                )


def _check_destructive_tool_without_confirm(
    report: ScanReport,
    tool_calls: list["Step"],
) -> None:
    """Detect irreversible tool calls made without a prior confirmation step.

    Bug class: Irreversible-Action-Without-Confirmation (tool-call variant).
    Observed in: pydantic-ai bank_support (live run).

    Some agents call block_card / cancel_subscription / charge_card directly
    as tool calls rather than encoding them in agent_finish output. This check
    catches that variant — the action fires with no confirm_action step before it.
    """
    _DESTRUCTIVE_TOOLS = re.compile(
        r"^(block_card|cancel_card|freeze_account|cancel_subscription"
        r"|charge_card|delete_account|lock_account|suspend_user)$",
        re.I,
    )
    # Match any tool whose name starts with "confirm" or "verify", plus common
    # explicit names. This covers: confirm_action, confirm_user, verify_permissions, etc.
    _CONFIRM_TOOLS = re.compile(
        r"^(confirm\w*|verify\w*|request_confirmation|get_confirmation|user_confirm|explicit_confirm)$",
        re.I,
    )
    for step in tool_calls:
        if not _DESTRUCTIVE_TOOLS.match(step.name):
            continue
        any_confirm_before = any(
            _CONFIRM_TOOLS.match(s.name) and s.index < step.index
            for s in tool_calls
        )
        if not any_confirm_before:
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="irreversible_action_without_confirmation",
                    title=f"'{step.name}' called without prior confirmation step",
                    detail=(
                        f"'{step.name}' (step {step.index}) is an irreversible action.\n"
                        f"No confirm_action or equivalent was called before it.\n"
                        f"The action fires immediately with no user consent checkpoint.\n"
                        f"Guard: always call confirm_action before irreversible tools."
                    ),
                    step_indices=[step.index],
                    suggested_assertion=f"never_before({step.name!r}, 'confirm_action')",
                )
            )


def _check_irreversible_in_finish(
    report: ScanReport,
    trace: "Trace",
) -> None:
    """Detect irreversible actions embedded in agent_finish output without a confirmation step.

    Bug class: Irreversible-Action-Without-Confirmation.
    Observed in: pydantic-ai bank_support, openai-cs-agents-demo.

    Some agents encode irreversible actions (block_card, cancel_subscription,
    charge_card) as boolean fields in their structured output rather than as
    separate tool calls. This means the action fires with NO preceding confirmation
    tool call — the user never gets a chance to say no.
    """
    from trajex.trace import StepType

    _IRREVERSIBLE_KEYS = {
        "block_card", "cancel_card", "freeze_account",
        "cancel_subscription", "charge_card", "delete_account",
        "lock_account", "suspend_user",
    }
    _CONFIRM_TOOLS = re.compile(
        r"^(confirm\w*|verify\w*|request_confirmation|get_confirmation|user_confirm|explicit_confirm)$",
        re.I,
    )

    # Check if any confirmation tool was called
    tool_calls = trace.tool_calls()
    any_confirm = any(_CONFIRM_TOOLS.match(s.name) for s in tool_calls)

    for step in trace.steps:
        if step.step_type != StepType.AGENT_FINISH:
            continue
        out = step.output if isinstance(step.output, dict) else {}
        triggered = [k for k in _IRREVERSIBLE_KEYS if out.get(k) is True]
        if triggered and not any_confirm:
            report.findings.append(
                ScanFinding(
                    level="FAIL",
                    check_name="irreversible_action_without_confirmation",
                    title=f"Irreversible action(s) in finish output without confirmation step",
                    detail=(
                        f"agent_finish output contains {triggered} = True.\n"
                        f"No confirmation tool call preceded this decision.\n"
                        f"The action is taken immediately and silently — the user cannot intervene.\n"
                        f"In production: a customer's card/account is affected without consent.\n"
                        f"Guard: call an explicit confirm() tool before setting irreversible flags."
                    ),
                    step_indices=[step.index],
                    suggested_assertion="",
                )
            )
